cloud_gateway_ip: 192.168.178.1
sensors:
  - script_path: 'sensors/sensor_mic.py'
    send_interval: 10
    reads_per_minute: 240
    module_id: 0
    module_name: 'Test Sensor 1'
    params:
      port: 0
  - script_path: 'sensors/sensor_dht.py'
    send_interval: 10
    reads_per_minute: 40
    module_id: 0
    module_name: 'Test Sensor 1'
    params:
      port: 7
  - script_path: 'sensors/sensor_pir.py'
    send_interval: 10
    reads_per_minute: 240
    module_id: 0
    module_name: 'Test Sensor 1'
    params:
      port: 8
actuators:
  - script_path: 'actuators/thermostat.py'


