cloud_gateway_ip: '52.207.119.17'
cloud_gateway_port: 9001
sensors:
  - script_path: 'sensors/sensor_dht.py'
    send_interval: 10
    reads_per_minute: 40
    module_name: 'dht_0'
    tags:
      - temp
      - humidity
    params:
      port: 7
      dht_type: 0
  - script_path: 'sensors/sensor_pir.py'
    send_interval: 10
    reads_per_minute: 240
    module_name: 'pir_0'
    tags:
      - pir
    params:
      port: 8
actuators:
  - script_path: 'actuators/thermostat.py'


