cloud_gateway_ip: '52.207.119.17'
cloud_gateway_port: 9001
sensors:
  - script_path: 'sensors/sensor_pir.py'
    send_interval: 10
    reads_per_minute: 240
    module_id: 0
    module_name: 'pir_0'
    params:
      port: 8

